language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
    secure: usRDLkwgFuOK0bwiGodg37ERVmWT73kef+DbKh2OUHthVA7tamifEUUU+8LtH+y2e1PxeHwWTq+cAK/P+QInH9vVIwaYvwKgDfHrkctkqj9D1RUuaaSW5VCiW9mKPBTmuxO/obj960srUMWYspkQ8O0vl3bQxJDFpGBuVCtCVHFumoxIDfpaxxiCOdm1J+r58yN3QUnZU8ALGl68GA9bi/O2BLASU7DxA23dfuWAp9d5AyPyO7S90kI72awpmnDc1UpgaV3zaFHkW2OAuQgRgvpM4AwHXJe9FBvrVqleVuE/DD39hp34NXuJrR2IKjUsObai+M4fuh5vNegO5qCmj2Uh/iGXe1Y4yupnb9mjOd+sm8KkYeJfGXPqMFLnC2axpSX4MS86kcL+1PMnxezj2j03Lb5RDBbYSQffnwFdpq36gZNJDeHAEoYUngTJfvZ1w0yiPMPgBjHVuX9BD0bgdRO83WQDWO/ACQqSyMSzt8KIT5kCbU/CHXy71dNoBTfTQfCW/CE2q6qGYEeUzaaerNQTwPLoUHr1BfSJTI1mRVQqeCgsPEWCmuSDs7kSkmp+utXvu1he3vggG2B3dNIYlH7zuCLSB/dsm3HrZQiLElWZ4uoRY0rrNvBsZZIP7ld+c0FQNNnbvLKNgZYhSvXt3SwFxl7n1gGTKfr6vgsqVoQ=
